//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CDClassLibrary.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CDClassLibrary.Language.ResourceLang", typeof(ResourceLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string TAirPressureState_asError {
            get {
                return ResourceManager.GetString("TAirPressureState_asError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string TAirPressureState_asNormal {
            get {
                return ResourceManager.GetString("TAirPressureState_asNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string TAutoDoorState_dsDock {
            get {
                return ResourceManager.GetString("TAutoDoorState_dsDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        internal static string TAutoDoorState_dsNull {
            get {
                return ResourceManager.GetString("TAutoDoorState_dsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string TAutoDoorState_dsOpen {
            get {
                return ResourceManager.GetString("TAutoDoorState_dsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备故障 的本地化字符串。
        /// </summary>
        internal static string TCageState_CageAlarm {
            get {
                return ResourceManager.GetString("TCageState_CageAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备正常 的本地化字符串。
        /// </summary>
        internal static string TCageState_CageNormal {
            get {
                return ResourceManager.GetString("TCageState_CageNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步次类型相同时，累计计算 的本地化字符串。
        /// </summary>
        internal static string TCapEnCalculateMode_AddUp {
            get {
                return ResourceManager.GetString("TCapEnCalculateMode_AddUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每个步次从零开始计算 的本地化字符串。
        /// </summary>
        internal static string TCapEnCalculateMode_StartAnew {
            get {
                return ResourceManager.GetString("TCapEnCalculateMode_StartAnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化不对 的本地化字符串。
        /// </summary>
        internal static string TComState_Error {
            get {
                return ResourceManager.GetString("TComState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源故障通讯不上 的本地化字符串。
        /// </summary>
        internal static string TComState_Null {
            get {
                return ResourceManager.GetString("TComState_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string TComState_OK {
            get {
                return ResourceManager.GetString("TComState_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接触测试完成 的本地化字符串。
        /// </summary>
        internal static string TContactTestFlag_Complete {
            get {
                return ResourceManager.GetString("TContactTestFlag_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接触测试启动失败：流程数据无效 的本地化字符串。
        /// </summary>
        internal static string TContactTestFlag_Error1 {
            get {
                return ResourceManager.GetString("TContactTestFlag_Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接触测试启动失败：软件授权到期 的本地化字符串。
        /// </summary>
        internal static string TContactTestFlag_Error2 {
            get {
                return ResourceManager.GetString("TContactTestFlag_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接触测试启动失败：平台故障 的本地化字符串。
        /// </summary>
        internal static string TContactTestFlag_Error3 {
            get {
                return ResourceManager.GetString("TContactTestFlag_Error3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始状态或接触测试中 的本地化字符串。
        /// </summary>
        internal static string TContactTestFlag_Init {
            get {
                return ResourceManager.GetString("TContactTestFlag_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CO超标报警 的本地化字符串。
        /// </summary>
        internal static string TCOState_asAlarm {
            get {
                return ResourceManager.GetString("TCOState_asAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传感器异常或没有连接 的本地化字符串。
        /// </summary>
        internal static string TCOState_asInitError {
            get {
                return ResourceManager.GetString("TCOState_asInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string TCOState_asNormal {
            get {
                return ResourceManager.GetString("TCOState_asNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string TCurtainState_csError {
            get {
                return ResourceManager.GetString("TCurtainState_csError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布幕伸出 的本地化字符串。
        /// </summary>
        internal static string TCurtainState_csExtend {
            get {
                return ResourceManager.GetString("TCurtainState_csExtend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布幕收回 的本地化字符串。
        /// </summary>
        internal static string TCurtainState_csWithdrawal {
            get {
                return ResourceManager.GetString("TCurtainState_csWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气缸闭合 的本地化字符串。
        /// </summary>
        internal static string TCylinderStatorState_dsDock {
            get {
                return ResourceManager.GetString("TCylinderStatorState_dsDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气缸运动中 的本地化字符串。
        /// </summary>
        internal static string TCylinderStatorState_dsRunning {
            get {
                return ResourceManager.GetString("TCylinderStatorState_dsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气缸张开 的本地化字符串。
        /// </summary>
        internal static string TCylinderStatorState_dsUndock {
            get {
                return ResourceManager.GetString("TCylinderStatorState_dsUndock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台健康 的本地化字符串。
        /// </summary>
        internal static string TDeviceState_efNull {
            get {
                return ResourceManager.GetString("TDeviceState_efNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平台有故障 的本地化字符串。
        /// </summary>
        internal static string TDeviceState_ErrorOther {
            get {
                return ResourceManager.GetString("TDeviceState_ErrorOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 故障流程不能工作 的本地化字符串。
        /// </summary>
        internal static string TDeviceState_ProCannotWorkError {
            get {
                return ResourceManager.GetString("TDeviceState_ProCannotWorkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一般故障流程可以工作 的本地化字符串。
        /// </summary>
        internal static string TDeviceState_ProCanWorkError {
            get {
                return ResourceManager.GetString("TDeviceState_ProCanWorkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通道有保护 的本地化字符串。
        /// </summary>
        internal static string TDeviceState_protecte {
            get {
                return ResourceManager.GetString("TDeviceState_protecte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 到位 的本地化字符串。
        /// </summary>
        internal static string TDoorState_dsDock {
            get {
                return ResourceManager.GetString("TDoorState_dsDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        internal static string TDoorState_dsNull {
            get {
                return ResourceManager.GetString("TDoorState_dsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有急停按下 的本地化字符串。
        /// </summary>
        internal static string TEmgButtonState_esEMG {
            get {
                return ResourceManager.GetString("TEmgButtonState_esEMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有急停 的本地化字符串。
        /// </summary>
        internal static string TEmgButtonState_esNull {
            get {
                return ResourceManager.GetString("TEmgButtonState_esNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有输出 的本地化字符串。
        /// </summary>
        internal static string TEtalonPowerState_NoOutput {
            get {
                return ResourceManager.GetString("TEtalonPowerState_NoOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无输出 的本地化字符串。
        /// </summary>
        internal static string TEtalonPowerState_WithOutput {
            get {
                return ResourceManager.GetString("TEtalonPowerState_WithOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 故障 的本地化字符串。
        /// </summary>
        internal static string TFanState_fsError {
            get {
                return ResourceManager.GetString("TFanState_fsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 的本地化字符串。
        /// </summary>
        internal static string TFanState_fsRun {
            get {
                return ResourceManager.GetString("TFanState_fsRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string TFanState_fsStop {
            get {
                return ResourceManager.GetString("TFanState_fsStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测完成 的本地化字符串。
        /// </summary>
        internal static string TFlowValveState_Completed {
            get {
                return ResourceManager.GetString("TFlowValveState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测故障 的本地化字符串。
        /// </summary>
        internal static string TFlowValveState_Error {
            get {
                return ResourceManager.GetString("TFlowValveState_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化 的本地化字符串。
        /// </summary>
        internal static string TFlowValveState_Init {
            get {
                return ResourceManager.GetString("TFlowValveState_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始检测 的本地化字符串。
        /// </summary>
        internal static string TFlowValveState_Start {
            get {
                return ResourceManager.GetString("TFlowValveState_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测中 的本地化字符串。
        /// </summary>
        internal static string TFlowValveState_Test {
            get {
                return ResourceManager.GetString("TFlowValveState_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 挡住 的本地化字符串。
        /// </summary>
        internal static string TForkState_fsDock {
            get {
                return ResourceManager.GetString("TForkState_fsDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没挡 的本地化字符串。
        /// </summary>
        internal static string TForkState_fsUndock {
            get {
                return ResourceManager.GetString("TForkState_fsUndock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灭 的本地化字符串。
        /// </summary>
        internal static string ThreeColorLightState_Extinguish {
            get {
                return ResourceManager.GetString("ThreeColorLightState_Extinguish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绿灯亮 的本地化字符串。
        /// </summary>
        internal static string ThreeColorLightState_Green {
            get {
                return ResourceManager.GetString("ThreeColorLightState_Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 红灯亮 的本地化字符串。
        /// </summary>
        internal static string ThreeColorLightState_Red {
            get {
                return ResourceManager.GetString("ThreeColorLightState_Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 黄灯亮 的本地化字符串。
        /// </summary>
        internal static string ThreeColorLightState_Yellow {
            get {
                return ResourceManager.GetString("ThreeColorLightState_Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源关闭 的本地化字符串。
        /// </summary>
        internal static string TInverterPowerState_asAlarm {
            get {
                return ResourceManager.GetString("TInverterPowerState_asAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源错误 的本地化字符串。
        /// </summary>
        internal static string TInverterPowerState_asInitError {
            get {
                return ResourceManager.GetString("TInverterPowerState_asInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源开启 的本地化字符串。
        /// </summary>
        internal static string TInverterPowerState_asNormal {
            get {
                return ResourceManager.GetString("TInverterPowerState_asNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源故障通讯不上 的本地化字符串。
        /// </summary>
        internal static string TInverterStateTwowin_asAlarm {
            get {
                return ResourceManager.GetString("TInverterStateTwowin_asAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化不对 的本地化字符串。
        /// </summary>
        internal static string TInverterStateTwowin_asInitError {
            get {
                return ResourceManager.GetString("TInverterStateTwowin_asInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string TInverterStateTwowin_asNormal {
            get {
                return ResourceManager.GetString("TInverterStateTwowin_asNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测漏完成 的本地化字符串。
        /// </summary>
        internal static string TMaintPreState_Completed {
            get {
                return ResourceManager.GetString("TMaintPreState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测漏失败 的本地化字符串。
        /// </summary>
        internal static string TMaintPreState_Failed {
            get {
                return ResourceManager.GetString("TMaintPreState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始状态 的本地化字符串。
        /// </summary>
        internal static string TMaintPreState_Init {
            get {
                return ResourceManager.GetString("TMaintPreState_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保压检测 的本地化字符串。
        /// </summary>
        internal static string TMaintPreState_PressureHolding {
            get {
                return ResourceManager.GetString("TMaintPreState_PressureHolding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 漏率检测 的本地化字符串。
        /// </summary>
        internal static string TMaintPreState_RateDetection {
            get {
                return ResourceManager.GetString("TMaintPreState_RateDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稳压检测 的本地化字符串。
        /// </summary>
        internal static string TMaintPreState_StablePressureSetection {
            get {
                return ResourceManager.GetString("TMaintPreState_StablePressureSetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测漏抽真空 的本地化字符串。
        /// </summary>
        internal static string TMaintPreState_Vacuuming {
            get {
                return ResourceManager.GetString("TMaintPreState_Vacuuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常模式，流程工作中 的本地化字符串。
        /// </summary>
        internal static string TMcuWorkState_Auto1 {
            get {
                return ResourceManager.GetString("TMcuWorkState_Auto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常模式，空闲状态 的本地化字符串。
        /// </summary>
        internal static string TMcuWorkState_Auto2 {
            get {
                return ResourceManager.GetString("TMcuWorkState_Auto2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动模式，不可退出 的本地化字符串。
        /// </summary>
        internal static string TMcuWorkState_Manual1 {
            get {
                return ResourceManager.GetString("TMcuWorkState_Manual1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动模式，可退出 的本地化字符串。
        /// </summary>
        internal static string TMcuWorkState_Manual2 {
            get {
                return ResourceManager.GetString("TMcuWorkState_Manual2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构在执行流程动作中 的本地化字符串。
        /// </summary>
        internal static string TMechanicalWorkSate_AtWork {
            get {
                return ResourceManager.GetString("TMechanicalWorkSate_AtWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构动作正常完成 的本地化字符串。
        /// </summary>
        internal static string TMechanicalWorkSate_Completion {
            get {
                return ResourceManager.GetString("TMechanicalWorkSate_Completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化状态 的本地化字符串。
        /// </summary>
        internal static string TMechanicalWorkSate_Init {
            get {
                return ResourceManager.GetString("TMechanicalWorkSate_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构动作执行超时 的本地化字符串。
        /// </summary>
        internal static string TMechanicalWorkSate_Timeout {
            get {
                return ResourceManager.GetString("TMechanicalWorkSate_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负压调整完成 的本地化字符串。
        /// </summary>
        internal static string TNegatPreState_Completed {
            get {
                return ResourceManager.GetString("TNegatPreState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始状态 的本地化字符串。
        /// </summary>
        internal static string TNegatPreState_Init {
            get {
                return ResourceManager.GetString("TNegatPreState_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负压调整中 的本地化字符串。
        /// </summary>
        internal static string TNegatPreState_InProgress {
            get {
                return ResourceManager.GetString("TNegatPreState_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负压调整超时 的本地化字符串。
        /// </summary>
        internal static string TNegatPreState_TimedOut {
            get {
                return ResourceManager.GetString("TNegatPreState_TimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续下一步 的本地化字符串。
        /// </summary>
        internal static string TNextMode_Next {
            get {
                return ResourceManager.GetString("TNextMode_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停，等待上位机重新启动命令 的本地化字符串。
        /// </summary>
        internal static string TNextMode_Suspend {
            get {
                return ResourceManager.GetString("TNextMode_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产模式 的本地化字符串。
        /// </summary>
        internal static string TOperationMode_Production {
            get {
                return ResourceManager.GetString("TOperationMode_Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试模式 的本地化字符串。
        /// </summary>
        internal static string TOperationMode_Test {
            get {
                return ResourceManager.GetString("TOperationMode_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无消防 的本地化字符串。
        /// </summary>
        internal static string TPLCFireControlState_NoControl {
            get {
                return ResourceManager.GetString("TPLCFireControlState_NoControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有消防 的本地化字符串。
        /// </summary>
        internal static string TPLCFireControlState_WithControl {
            get {
                return ResourceManager.GetString("TPLCFireControlState_WithControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测堵完成 的本地化字符串。
        /// </summary>
        internal static string TPluggingState_Completed {
            get {
                return ResourceManager.GetString("TPluggingState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测堵失败 的本地化字符串。
        /// </summary>
        internal static string TPluggingState_Failed {
            get {
                return ResourceManager.GetString("TPluggingState_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始状态 的本地化字符串。
        /// </summary>
        internal static string TPluggingState_Init {
            get {
                return ResourceManager.GetString("TPluggingState_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测堵稳压检测 的本地化字符串。
        /// </summary>
        internal static string TPluggingState_StablePressureSetection {
            get {
                return ResourceManager.GetString("TPluggingState_StablePressureSetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测堵抽真空 的本地化字符串。
        /// </summary>
        internal static string TPluggingState_Vacuuming {
            get {
                return ResourceManager.GetString("TPluggingState_Vacuuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始化状态 的本地化字符串。
        /// </summary>
        internal static string TPowerFailFlag_pfInit {
            get {
                return ResourceManager.GetString("TPowerFailFlag_pfInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常工作状态 的本地化字符串。
        /// </summary>
        internal static string TPowerFailFlag_pfNormal {
            get {
                return ResourceManager.GetString("TPowerFailFlag_pfNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常掉电 的本地化字符串。
        /// </summary>
        internal static string TPowerFailFlag_pfNormalStop {
            get {
                return ResourceManager.GetString("TPowerFailFlag_pfNormalStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常掉电需要上位机下发掉电清除或恢复 的本地化字符串。
        /// </summary>
        internal static string TPowerFailFlag_pfOccurred {
            get {
                return ResourceManager.GetString("TPowerFailFlag_pfOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复失败 的本地化字符串。
        /// </summary>
        internal static string TPowerFailFlag_pfResumeError {
            get {
                return ResourceManager.GetString("TPowerFailFlag_pfResumeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掉电恢复或清除执行中 的本地化字符串。
        /// </summary>
        internal static string TPowerFailFlag_pfResuming {
            get {
                return ResourceManager.GetString("TPowerFailFlag_pfResuming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        internal static string TPreState_Completion {
            get {
                return ResourceManager.GetString("TPreState_Completion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始状态 的本地化字符串。
        /// </summary>
        internal static string TPreState_Init {
            get {
                return ResourceManager.GetString("TPreState_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时 的本地化字符串。
        /// </summary>
        internal static string TPreStatee_Overtime {
            get {
                return ResourceManager.GetString("TPreStatee_Overtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动运行中 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfAutoInProc {
            get {
                return ResourceManager.GetString("TProcessFlag_pfAutoInProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动停止 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfAutoProcEnd {
            get {
                return ResourceManager.GetString("TProcessFlag_pfAutoProcEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程结束错误 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfEndNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfEndNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接触测试 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfInContactTest {
            get {
                return ResourceManager.GetString("TProcessFlag_pfInContactTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程运行中错误 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfInProcNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfInProcNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保压测试 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfMaintPreTest {
            get {
                return ResourceManager.GetString("TProcessFlag_pfMaintPreTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保压错误 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfMaintPreTestNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfMaintPreTestNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动运行中 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfManualInProc {
            get {
                return ResourceManager.GetString("TProcessFlag_pfManualInProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动停止 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfManualProcEnd {
            get {
                return ResourceManager.GetString("TProcessFlag_pfManualProcEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负压测试 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfNegatPreTest {
            get {
                return ResourceManager.GetString("TProcessFlag_pfNegatPreTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负压错误 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfNegatPreTestNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfNegatPreTestNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无电池通道检测 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfNoCellCheck {
            get {
                return ResourceManager.GetString("TProcessFlag_pfNoCellCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无电池通道检测错误 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfNoCellCheckNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfNoCellCheckNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程运行中 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfOnMnStop {
            get {
                return ResourceManager.GetString("TProcessFlag_pfOnMnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程运行中错误 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfOnMnStopNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfOnMnStopNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测堵测试 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfPluggingTest {
            get {
                return ResourceManager.GetString("TProcessFlag_pfPluggingTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测堵错误 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfPluggingTestNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfPluggingTestNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程准备 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfReady {
            get {
                return ResourceManager.GetString("TProcessFlag_pfReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接触测试 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitContactTest {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitContactTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接触测试错误 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitContactTestNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitContactTestNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动停止 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitContinue {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程恢复失败 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitContinueNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitContinueNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程获取或发送 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitFixProc {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitFixProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程获取或发送失败 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitFixProcNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitFixProcNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程等待时错误 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCV测试 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitOCVTest {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitOCVTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OCV测试失败 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitOCVTestNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitOCVTestNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程启动 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitProcStart {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitProcStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程启动失败 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_pfWaitProcStartNG {
            get {
                return ResourceManager.GetString("TProcessFlag_pfWaitProcStartNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始状态 的本地化字符串。
        /// </summary>
        internal static string TProcessFlag_ssInit {
            get {
                return ResourceManager.GetString("TProcessFlag_ssInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校正流程 的本地化字符串。
        /// </summary>
        internal static string TProcessMode_Calibration {
            get {
                return ResourceManager.GetString("TProcessMode_Calibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计量流程 的本地化字符串。
        /// </summary>
        internal static string TProcessMode_Measurement {
            get {
                return ResourceManager.GetString("TProcessMode_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常流程 的本地化字符串。
        /// </summary>
        internal static string TProcessMode_Normal {
            get {
                return ResourceManager.GetString("TProcessMode_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始状态 的本地化字符串。
        /// </summary>
        internal static string TProcessStatus_Init {
            get {
                return ResourceManager.GetString("TProcessStatus_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string TProcessStatus_Resume {
            get {
                return ResourceManager.GetString("TProcessStatus_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string TProcessStatus_Running {
            get {
                return ResourceManager.GetString("TProcessStatus_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        internal static string TProcessStatus_Stop {
            get {
                return ResourceManager.GetString("TProcessStatus_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        internal static string TProcessStatus_Suspend {
            get {
                return ResourceManager.GetString("TProcessStatus_Suspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 弹出 的本地化字符串。
        /// </summary>
        internal static string TRESETButtonStates_esNull {
            get {
                return ResourceManager.GetString("TRESETButtonStates_esNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下 的本地化字符串。
        /// </summary>
        internal static string TRESETButtonStates_esRESET {
            get {
                return ResourceManager.GetString("TRESETButtonStates_esRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按下 的本地化字符串。
        /// </summary>
        internal static string TResKeyStates_Down {
            get {
                return ResourceManager.GetString("TResKeyStates_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋出 的本地化字符串。
        /// </summary>
        internal static string TResKeyStates_Up {
            get {
                return ResourceManager.GetString("TResKeyStates_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        internal static string TSecureState_ssNo {
            get {
                return ResourceManager.GetString("TSecureState_ssNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全 的本地化字符串。
        /// </summary>
        internal static string TSecureState_ssSecure {
            get {
                return ResourceManager.GetString("TSecureState_ssSecure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动门传感器报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efAutoDoorError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efAutoDoorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中框风机报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efCentreFanError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efCentreFanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布幕伸出报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efExtendError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efExtendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全门报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efFireDoorError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efFireDoorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气缸到位报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efProbeDownError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efProbeDownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气缸零位报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efProbeUpError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efProbeUpError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维修侧风机报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efSideFanError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efSideFanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调速水冷风机报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efSpeedGovernFanError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efSpeedGovernFanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 顶部风机报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efTopFanError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efTopFanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘传感器 1 报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efTray1Error {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efTray1Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘传感器 2 报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efTray2Error {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efTray2Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘缺角传感器报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efTrayAngleError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efTrayAngleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 水冷风机报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efWaterFanError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efWaterFanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布幕收回报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_efWithdrawalError {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_efWithdrawalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货叉传感器报警 的本地化字符串。
        /// </summary>
        internal static string TSensorsEMGFault_sfFock {
            get {
                return ResourceManager.GetString("TSensorsEMGFault_sfFock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效 的本地化字符串。
        /// </summary>
        internal static string TSensorStates_Null {
            get {
                return ResourceManager.GetString("TSensorStates_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效 的本地化字符串。
        /// </summary>
        internal static string TSensorStates_OK {
            get {
                return ResourceManager.GetString("TSensorStates_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气压报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efAir {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efAir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电池温度报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efBoardTemp {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efBoardTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CO报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efCO {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构风机报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efFan {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efFan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消防报警（PLC 给机笼） 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efFireControl {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efFireControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efFromPC {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efFromPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 逆变器报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efInverter {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efInverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保压报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efMaintPreState {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efMaintPreState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按钮急停报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efManual {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PC命令急停 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efManualPC {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efManualPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负压报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efNegatPreState {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efNegatPreState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测堵报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efPluggingState {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efPluggingState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电源部断电报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efPowerSupply {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efPowerSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 烟雾报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efSmog {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efSmog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构部温度报警 的本地化字符串。
        /// </summary>
        internal static string TSeriousEMGFault_efTemp {
            get {
                return ResourceManager.GetString("TSeriousEMGFault_efTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 烟雾超标报警 的本地化字符串。
        /// </summary>
        internal static string TSmogState_asAlarm {
            get {
                return ResourceManager.GetString("TSmogState_asAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传感器异常或没有连接 的本地化字符串。
        /// </summary>
        internal static string TSmogState_asInitError {
            get {
                return ResourceManager.GetString("TSmogState_asInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string TSmogState_asNormal {
            get {
                return ResourceManager.GetString("TSmogState_asNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 充放电测试报警 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssChargeDis {
            get {
                return ResourceManager.GetString("TStageState_ssChargeDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构错误 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssEMG {
            get {
                return ResourceManager.GetString("TStageState_ssEMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 初始状态 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssInit {
            get {
                return ResourceManager.GetString("TStageState_ssInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 真空测试报警 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssMaintain {
            get {
                return ResourceManager.GetString("TStageState_ssMaintain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无通信 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssOff {
            get {
                return ResourceManager.GetString("TStageState_ssOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssOverTime {
            get {
                return ResourceManager.GetString("TStageState_ssOverTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上位机报警 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssPCAlarm {
            get {
                return ResourceManager.GetString("TStageState_ssPCAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 掉电标记 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssPowerDown {
            get {
                return ResourceManager.GetString("TStageState_ssPowerDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作业完成 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssProcessEnd {
            get {
                return ResourceManager.GetString("TStageState_ssProcessEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程准备 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssReady {
            get {
                return ResourceManager.GetString("TStageState_ssReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程中 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssRunning {
            get {
                return ResourceManager.GetString("TStageState_ssRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 烟雾报警 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssSmoke {
            get {
                return ResourceManager.GetString("TStageState_ssSmoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备停止 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssStop {
            get {
                return ResourceManager.GetString("TStageState_ssStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超温报警 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssTemp {
            get {
                return ResourceManager.GetString("TStageState_ssTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘位置错误 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssTrayError {
            get {
                return ResourceManager.GetString("TStageState_ssTrayError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘进入 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssTrayIn {
            get {
                return ResourceManager.GetString("TStageState_ssTrayIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未启用 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssVacancy {
            get {
                return ResourceManager.GetString("TStageState_ssVacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程等待 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssWait {
            get {
                return ResourceManager.GetString("TStageState_ssWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待出库 的本地化字符串。
        /// </summary>
        internal static string TStageState_ssWaitOutbound {
            get {
                return ResourceManager.GetString("TStageState_ssWaitOutbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恒流充电 的本地化字符串。
        /// </summary>
        internal static string TStepMode_CC {
            get {
                return ResourceManager.GetString("TStepMode_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恒流充到恒压充 的本地化字符串。
        /// </summary>
        internal static string TStepMode_CCCV {
            get {
                return ResourceManager.GetString("TStepMode_CCCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恒功率充电 的本地化字符串。
        /// </summary>
        internal static string TStepMode_CP {
            get {
                return ResourceManager.GetString("TStepMode_CP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恒压充电 的本地化字符串。
        /// </summary>
        internal static string TStepMode_CV {
            get {
                return ResourceManager.GetString("TStepMode_CV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 循环步次 的本地化字符串。
        /// </summary>
        internal static string TStepMode_CYCLE {
            get {
                return ResourceManager.GetString("TStepMode_CYCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恒流放电 的本地化字符串。
        /// </summary>
        internal static string TStepMode_DC {
            get {
                return ResourceManager.GetString("TStepMode_DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恒流放到恒压放 的本地化字符串。
        /// </summary>
        internal static string TStepMode_DCDV {
            get {
                return ResourceManager.GetString("TStepMode_DCDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恒功率放电 的本地化字符串。
        /// </summary>
        internal static string TStepMode_DP {
            get {
                return ResourceManager.GetString("TStepMode_DP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恒压放电 的本地化字符串。
        /// </summary>
        internal static string TStepMode_DV {
            get {
                return ResourceManager.GetString("TStepMode_DV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开路测试 的本地化字符串。
        /// </summary>
        internal static string TStepMode_OCV {
            get {
                return ResourceManager.GetString("TStepMode_OCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休眠 的本地化字符串。
        /// </summary>
        internal static string TStepMode_REST {
            get {
                return ResourceManager.GetString("TStepMode_REST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳过 的本地化字符串。
        /// </summary>
        internal static string TStepMode_SKIP {
            get {
                return ResourceManager.GetString("TStepMode_SKIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 等待 的本地化字符串。
        /// </summary>
        internal static string TStepMode_WAIT {
            get {
                return ResourceManager.GetString("TStepMode_WAIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 温度超标报警 的本地化字符串。
        /// </summary>
        internal static string TTempState_asAlarm {
            get {
                return ResourceManager.GetString("TTempState_asAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传感器异常或没有连接 的本地化字符串。
        /// </summary>
        internal static string TTempState_asInitError {
            get {
                return ResourceManager.GetString("TTempState_asInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string TTempState_asNormal {
            get {
                return ResourceManager.GetString("TTempState_asNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘到位 的本地化字符串。
        /// </summary>
        internal static string TTrayState_dsDock {
            get {
                return ResourceManager.GetString("TTrayState_dsDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 托盘不到位 的本地化字符串。
        /// </summary>
        internal static string TTrayState_dsDockError {
            get {
                return ResourceManager.GetString("TTrayState_dsDockError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有托盘 的本地化字符串。
        /// </summary>
        internal static string TTrayState_dsUndock {
            get {
                return ResourceManager.GetString("TTrayState_dsUndock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string TVacuumState_asInitError {
            get {
                return ResourceManager.GetString("TVacuumState_asInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string TVacuumState_asNormal {
            get {
                return ResourceManager.GetString("TVacuumState_asNormal", resourceCulture);
            }
        }
    }
}
